### PR TITLE
Improve distribution things

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
See report in https://cpants.cpanauthors.org/release/SKIM/SNMP_Session-1.15

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
@sleinen Could we merge this PR?

**Review by sleinen — APPROVED** [review]
Thanks a lot!

**Comment by sleinen** [comment]
I merged this, added a few other unrelated changes, and tagged it with "v1.16".  @michal-josef-spacek can you upload this to CPAN (or tell me how I can do it myself—I now have a PAUSE account, but I'm a bit scared...).

**Comment by michal-josef-spacek** [comment]
@sleinen Thanks, I will look to it.

**Comment by michal-josef-spacek** [comment]
@sleinen Uploaded:
https://metacpan.org/release/SKIM/SNMP_Session-1.16
vs
https://metacpan.org/release/SKIM/SNMP_Session-1.15

I will wait for Kwalitee report and then could be nice to merge other PRs. This IPv6 bug is not nice.

**Comment by michal-josef-spacek** [comment]
Kwalitee report is fine: https://cpants.cpanauthors.org/release/SKIM/SNMP_Session-1.16
Thank you.

**Pull request merged**
